---
title: "Imputation"
author: "Kacper Kaszuba"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, fig.align = 'center')

library(dplyr)
```

# Loading data

```{r data preprocessing}
protein.groups <- readr::read_tsv('./data/proteinGroups.txt')

protein.groups <- protein.groups %>% filter(is.na(`Only identified by site`),
                         is.na(Reverse),
                         is.na(`Potential contaminant`))

# Extracting only necessary columns
LFQ <- protein.groups %>% select(starts_with('LFQ Intensity') & (ends_with('22') | ends_with('23') | ends_with('24')))
colnames(LFQ) <- gsub("^LFQ intensity ", "", colnames(LFQ))

LFQ[LFQ == 0] <- NA
LFQ.log <- log2(LFQ)
```

# Imputation

```{r imputation using Mateusz code}
impute_data = function(df, width = 0.3, downshift = 1.8, seed = 7694) {
  # df = data frame containing filtered data
  # Assumes missing data (in df) follows a narrowed and downshifted normal distribution
  
  #Seed for reproducibility (useful for later analysis)
  set.seed(seed)

  # Create new column indicating whether the values are imputed 
  # df$imputed = !is.finite(df$LFQvalue)

  # Imputation
  temp <- df 
  temp[!is.finite(temp)] = NA #make sure all non-finite values are really NA
  temp.sd = width * sd(temp, na.rm = TRUE) #shrink sd width
  temp.mean = mean(temp, na.rm = TRUE) - 
    downshift * sd(temp, na.rm = TRUE) #shift mean of imputed values
  n.missing = sum(is.na(temp))
  temp[is.na(temp)] = rnorm(n.missing, mean = temp.mean, sd = temp.sd) #replace NA with values from the new distribution
    
  df <- temp
    
  return(df)
}

# performing impute fxn for each col separately
LFQ.imp <- as.data.frame(lapply(LFQ.log, function(col) impute_data(col)))

# saving file with TOTALS columns
LFQ.TOTALS <- LFQ.imp %>% select(contains('TOTALS'))
write.csv(LFQ.TOTALS, file = './data/LFQ_raw_totals_imp.csv', sep=',', col.names = TRUE, row.names = FALSE)
```

# Additional opperations

```{r TOTALS data}
# Extracting only TOTALS data for wild type and knockout
LFQ_KO_TOTALS <- LFQ.imp %>% select(contains('KO_TOTALS'))
LFQ_WT_TOTALS <- LFQ.imp %>% select(contains('WT_TOTALS'))
```

```{r MITO data}
# Extracting only MITO data for wild type and knockout
LFQ_KO_MITO <- LFQ.imp %>% select(contains('KO_MITO'))
LFQ_WT_MITO <- LFQ.imp %>% select(contains('WT_MITO'))
```


```{r}
# Extracting nonimputed data
LFQ.log.totals <- LFQ.log %>%
    select(contains('TOTALS'))

colnames(LFQ.log.totals) <- gsub('_TOTALS_', '.', colnames(LFQ.log.totals))
write.csv(LFQ.log.totals, file='./data/nonimputed_lfq.csv', row.names=FALSE)
```

























